# Generated by Django 3.2.12 on 2022-02-08 22:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_num', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('telephone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{3,4}\\d{3,4}\\d{4}$', message='전화번호를 입력해 주세요.')])),
                ('opening_hours', models.TextField(blank=True)),
                ('table_count', models.IntegerField(default=0)),
                ('notice', models.TextField(blank=True)),
                ('intro', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='media/%Y/%m/%d')),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('content', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking', models.BooleanField(default=False)),
                ('pet', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('pack', models.BooleanField(default=False)),
                ('shop_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop')),
            ],
        ),
    ]
