# Generated by Django 3.2.9 on 2022-02-07 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=60, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
                ('name', models.CharField(db_index=True, max_length=60)),
                ('nickname', models.CharField(max_length=60, unique=True)),
                ('telephone', models.CharField(db_index=True, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{3}\\d{4}\\d{4}$', message='전화번호를 입력해 주세요.')])),
                ('authority', models.CharField(default=0, max_length=1)),
                ('signup_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
