# Generated by Django 3.2.12 on 2022-02-06 10:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=60)),
                ('nickname', models.CharField(max_length=60, unique=True)),
                ('telephone', models.CharField(db_index=True, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{3}\\d{4}\\d{4}$', message='전화번호를 입력해 주세요.')])),
                ('authority', models.CharField(default=0, max_length=1)),
                ('signup_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
